---
title: "First Knit"
author: "Davy D."
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
I attended high school at Rosamond High school, I graduated in 2016. I prefer english to me it is alot easier and comes more naturally than Math. The numbers tend to get mixed up in my head making math alot more challenging. I did the best in English.  

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
I have a Apple Macbook. I'm a solid 5 on computer awareness, I don't use computers too often so it's always an experience.I do have internet access but being in Rosamond it is a bit shoddy.  
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  I prefer to be called Davy. My name is Davyonah but it gets annoying correcting people pronounciation of it. 
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  I want to achieve being an RN. I think my greatest interest would be biology  because i do like to know the inner workings of the body. I'm trying to achieve an associates and transfer to a 4 year.
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  I have gone to Mexico. I want to go to the Uk in the future. Ive never been in the military. I would want to join the navy seals because they go on interesting missions and their training looks intense and like an interesting experience.
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  I took math 115. I want aware about math 115 I will talk to the counselor about that though. I plan and attaining and A to become a nurse.
   
 






  




